# Copyright 2025 Jeff Hodsdon
# SPDX-License-Identifier: Apache-2.0

"""Swift Preview Package - Basic version.

Generated by rules_swift_previews module extension.
"""

load("@rules_swift_previews//internal:core.bzl", _swift_previews_package = "swift_previews_package")

swift_previews_package = _swift_previews_package

SWIFT_PREVIEW_EXCLUDES = [
    "Package.swift",
    "*+Previews.swift",
]
