# Copyright 2025 Jeff Hodsdon
# SPDX-License-Identifier: Apache-2.0

"""Swift Preview Package - With SwiftResources integration.

Generated by rules_swift_previews module extension.
Resource modules are auto-detected by rule kind and Swift accessors are generated.
"""

load("@rules_swift_previews//internal:core.bzl",
     "create_swift_previews_macro",
     "create_swift_previews_rule")

SWIFT_PREVIEW_EXCLUDES = [
    "Package.swift",
    "*+Previews.swift",
]

_swift_previews_package_rule = create_swift_previews_rule({
    "_sr": attr.label(
        default = Label("{sr_label}"),
        allow_single_file = True,
        executable = True,
        cfg = "exec",
    ),
})

swift_previews_package = create_swift_previews_macro(_swift_previews_package_rule)
