# Copyright 2025 Jeff Hodsdon
# SPDX-License-Identifier: Apache-2.0

"""Repository rule that generates the swift_preview_rules repository.

Generates a thin wrapper that optionally adds the sr binary for
Swift resource accessor generation.
"""

_DEFS_BASIC = '''"""Swift Preview Package - Basic version.

Generated by rules_swift_previews module extension.
"""

load("@rules_swift_previews//internal:core.bzl", _swift_previews_package = "swift_previews_package")
load("@rules_swift_previews//internal:providers.bzl", "SourceFilesInfo")

SWIFT_PREVIEW_EXCLUDES = [
    "Package.swift",
    "*+Previews.swift",
]

# Re-export for users
swift_previews_package = _swift_previews_package
'''

_DEFS_WITH_SR_TEMPLATE = '''"""Swift Preview Package - With SwiftResources sr binary.

Generated by rules_swift_previews module extension.
Resource modules are auto-detected and Swift accessors are generated.
"""

load("@rules_swift_previews//internal:core.bzl",
     "source_collector_aspect",
     "swift_previews_package_impl")
load("@rules_swift_previews//internal:providers.bzl", "SourceFilesInfo")

SWIFT_PREVIEW_EXCLUDES = [
    "Package.swift",
    "*+Previews.swift",
]

# Rule with sr binary for generating Swift resource accessors
_swift_previews_package_rule = rule(
    implementation = swift_previews_package_impl,
    attrs = {{
        "lib": attr.label(
            mandatory = True,
            aspects = [source_collector_aspect],
        ),
        "package_dir": attr.string(mandatory = True),
        "ios_version": attr.string(default = "18"),
        "macos_version": attr.string(default = ""),
        "tvos_version": attr.string(default = ""),
        "watchos_version": attr.string(default = ""),
        "visionos_version": attr.string(default = ""),
        "_sr": attr.label(
            default = "{sr_label}",
            allow_single_file = True,
            executable = True,
            cfg = "exec",
        ),
    }},
    executable = True,
)

def swift_previews_package(
        name,
        lib,
        ios_version = "18",
        macos_version = "",
        tvos_version = "",
        watchos_version = "",
        visionos_version = "",
        visibility = None):
    """Generate an SPM Package.swift for Xcode SwiftUI previews.

    With SwiftResources integration for generating Swift resource accessors.
    """
    _swift_previews_package_rule(
        name = name,
        lib = lib,
        package_dir = native.package_name(),
        ios_version = ios_version,
        macos_version = macos_version,
        tvos_version = tvos_version,
        watchos_version = watchos_version,
        visionos_version = visionos_version,
        visibility = visibility,
    )
'''

def _swift_preview_rules_repository_impl(ctx):
    """Generate the swift_preview_rules repository."""

    ctx.file(
        "BUILD.bazel",
        content = '''package(default_visibility = ["//visibility:public"])
exports_files(["defs.bzl"])
''',
    )

    if ctx.attr.enable_swift_resources and ctx.attr.sr_label:
        content = _DEFS_WITH_SR_TEMPLATE.format(sr_label = ctx.attr.sr_label)
        ctx.file("defs.bzl", content = content)
    else:
        ctx.file("defs.bzl", content = _DEFS_BASIC)

swift_preview_rules_repository = repository_rule(
    implementation = _swift_preview_rules_repository_impl,
    attrs = {
        "enable_swift_resources": attr.bool(
            default = False,
            doc = "Enable sr binary for Swift resource accessor generation.",
        ),
        "sr_label": attr.string(
            default = "",
            doc = "Canonical label string for the sr binary.",
        ),
    },
    doc = "Generates the swift_preview_rules repository.",
)
